tomcat_linuxwt:
    restart: always
    image: tomcat/centos7
    container_name: tomcat_linuxwt
    volumes:
       - /etc/localtime:/etc/localtime
       - /etc/timezone:/etc/timezone
       - $PWD/setclasspath.sh:/usr/local/tomcat/bin/setclasspath.sh
       - $PWD/logs:/usr/local/tomcat/logs
       - $PWD/.bashrc:/root/.bashrc
       - $PWD/project_code:/usr/local/tomcat/webapps/ROOT
    privileged: true
    ports:
       - "80:8080"
